### ISSUE TITLE
FileWriter: check hresult

### ISSUE THREAD

**Issue by olegolo** [shkollik/.NetMentoring#4]
If the function succeeds, the return value is an open handle to the specified file, device, named pipe, or mail slot.
If the function fails, the return value is INVALID_HANDLE_VALUE. To get extended error information, call GetLastError.
https://msdn.microsoft.com/en-us/library/aa363858(VS.85).aspx

if (_fileHandle.ToInt32() == -1)
    ThrowLastWin32Err();

Or like so https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.110).aspx

**Comment by olegolo** [comment]
Or like so
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.110).aspx

**Comment by shkollik** [comment]
modified "ThrowLastWin32Err" method to :      
  private void ThrowLastWin32Err()
        {
            if (_fileHandle.ToInt32() == -1)
                Marshal.ThrowExceptionForHR(Marshal.GetHRForLastWin32Error());
        }
